name: Publish
on:
  - workflow_dispatch


concurrency:
  group: "publish"
  cancel-in-progress: false


jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Assemble
        run: ./gradlew assemble --info -S --show-version


  check:
    name: Check
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Check
        run: ./gradlew check --info -S --show-version


  build-docs:
    name: Build Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Dokka Generate
        run: ./gradlew dokkaGenerate --info -S --show-version

  build-artifact-bundles:
    name: Build Artifact Bundles
    needs: check
    strategy:
        matrix:
          os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Artifact Bundle
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew --init-script ./.github/init.gradle.kts artifactBundle --info -S --show-version

      - name: Upload Artifact Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ env.WORKSPACE_ARTIFACT }}
          path: "./build/libs/maven-artifact-bundle.tgz"
          retention-days: 1


  merge-artifact-bundles:
    name: Merge Bundles
    needs: build-artifact-bundles
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifact Bundle
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-${{ env.WORKSPACE_ARTIFACT }}
          path: artifacts

      - name: Download MacOS Artifact Bundle
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-${{ env.WORKSPACE_ARTIFACT }}
          path: artifacts

      - name: Merge
        id: merge
        uses: TheMrMilchmann/merge-tarballs@master
        with:
          glob: artifacts/**
          archive: ./artifact-bundle.tar.gz

      - name: Upload Artifact Bundle
        uses: actions/upload-artifact@v4
        with:
          name: "artifact-bundle"
          path: ${{ steps.merge.outputs.archive }}


  central-upload:
    name: Upload to Central Portal
    needs: merge-artifact-bundles
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact Bundle
        uses: actions/download-artifact@v4
        with:
          name: "artifact-bundle"
          path: ./artifact-bundle.tar.gz

      - name: Upload to Central Portal
        uses: TheMrMilchmann/central-portal-actions/upload-deployment@v0
        with:
          username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          bundle: ./artifact-bundle.tar.gz
          publishing-type: "USER_MANAGED"
